=== thenlpist/nlptk/nlptk/jrdatamodel/jsonresume_schema_20250414.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "default": {},
  "title": "Resume",
  "required": [
    "basics",
    "work",
    "volunteer",
    "education",
    "awards",
    "certificates",
    "publications",
    "skills",
    "languages",
    "interests",
    "references",
    "projects"
  ],
  "properties": {
    "basics": {
      "type": "object",
      "default": {},
      "title": "Basics Schema",
      "required": [
        "name",
        "label",
        "email",
        "phone",
        "url",
        "summary",
        "location",
        "profiles"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "location": {
          "type": "object",
          "default": {},
          "title": "Basics-Location Schema",
          "required": [
            "city",
            "region",
            "address",
            "postalCode",
            "countryCode"
          ],
          "properties": {
            "address": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "region": {
              "type": "string"
            },
            "countryCode": {
              "type": "string"
            },
            "postalCode": {
              "type": "string"
            }
          }
        },
        "profiles": {
          "type": "array",
          "default": [],
          "title": "Basics-Profiles Schema",
          "items": [
            {
              "required": [
                "url"
              ],
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              }
            }
          ]
        }
      }
    },
    "work": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name",
            "location",
            "position",
            "url",
            "startDate",
            "endDate",
            "summary",
            "highlights"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "location": {
              "type": "string"
            },
            "position": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            },
            "summary": {
              "type": "string"
            },
            "highlights": {
              "type": "array",
              "default": [],
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    },
    "volunteer": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "organization",
            "position",
            "url",
            "startDate",
            "endDate",
            "summary",
            "highlights"
          ],
          "properties": {
            "organization": {
              "type": "string"
            },
            "position": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            },
            "summary": {
              "type": "string"
            },
            "highlights": {
              "type": "array",
              "default": [],
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    },
    "education": {
      "title": "Education",
      "type": "array",
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "institution",
            "url",
            "area",
            "startDate",
            "endDate",
            "studyType",
            "courses",
            "minors"
          ],
          "properties": {
            "institution": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "area": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            },
            "studyType": {
              "type": "string"
            },
            "courses": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "minors": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    },
    "awards": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "title",
            "awarder",
            "date",
            "summary"
          ],
          "properties": {
            "title": {
              "type": "string"
            },
            "awarder": {
              "type": "string"
            },
            "date": {
              "type": "string"
            },
            "summary": {
              "type": "string"
            }
          }
        }
      ]
    },
    "certificates": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name",
            "issuer",
            "date",
            "url"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "issuer": {
              "type": "string"
            },
            "date": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        }
      ]
    },
    "publications": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name",
            "publisher",
            "releaseDate",
            "summary"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "publisher": {
              "type": "string"
            },
            "releaseDate": {
              "type": "string"
            },
            "summary": {
              "type": "string"
            }
          }
        }
      ]
    },
    "skills": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name",
            "keywords"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "keywords": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    },
    "languages": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "language",
            "fluency"
          ],
          "properties": {
            "language": {
              "type": "string"
            },
            "fluency": {
              "type": "string"
            }
          }
        }
      ]
    },
    "interests": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "references": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name",
            "reference"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "reference": {
              "type": "string"
            }
          }
        }
      ]
    },
    "projects": {
      "type": "array",
      "default": [],
      "items": [
        {
          "type": "object",
          "default": {},
          "required": [
            "name",
            "description",
            "highlights",
            "startDate",
            "endDate",
            "url",
            "roles"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "highlights": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "roles": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

=== thenlpist/nlptk/nlptk/jrdatamodel/json_resume.json
{
  "$schema": "https://raw.githubusercontent.com/jsonresume/resume-schema/master/schema.json",
  "basics": {
    "name": "John Snow",
    "label": "Full Stack Engineer",
    "email": "snowy.john@gmail.com",
    "phone": "(555) 905-1234",
    "url": "https://www.me.com/snowy-john",
    "summary": "Highly skilled and detail-oriented software engineer with expertise in multiple programming languages",
    "location": {
      "city": "Bangor",
      "countryCode": "US",
      "region": "Maine",
      "address": "101 Cambridge Ave",
      "postalCode": "04401"
    },
    "profiles": [
      {
        "url": "https://linkedin.com/johnksnow"
      }
    ]
  },
  "work": [
    {
      "name": "Bitbucket",
      "location": "San Francisco, CA",
      "position": "Senior Software Engineer",
      "url": "https://www.atlassian.com/",
      "startDate": "2024-03-14",
      "endDate": "",
      "summary": "Bitbucket is a code hosting and collaboration platform built for teams, primarily using Git, owned by Atlassian.",
      "highlights": [
        "Developed and maintained scalable web applications using React.js and Node.js, ensuring high performance and responsiveness.",
        "Designed and implemented RESTful APIs to facilitate seamless communica/on between front-end and back-end systems."
      ]
    },
    {
      "name": "InnovateTech Labs",
      "location": "Seattle, WA",
      "position": "Senior Software Engineer",
      "url": "https://innovate-techlabs.com/",
      "startDate": "2021-09-15",
      "endDate": "2024-02-28",
      "summary": "IT consulting firm committed to driving innovation and delivering state-of-the-art solutions that propel businesses into the digital age.",
      "highlights": [
        "Supported senior developers in building and maintaining web applications using HTML, CSS, and JavaScript.",
        "Assisted in the development of enterprise-level applications using Java and SAP ABAP, ensuring compliance with client requirements."
      ]
    }
  ],
  "volunteer": [
    {
      "organization": "Petro Rabigh",
      "position": "Worker Committee",
      "url": "https://example.com/",
      "startDate": "2020-01-07",
      "endDate": "2021-12-24",
      "summary": "Petro Rabigh is a Saudi Arabian petrochemical company, a joint venture between Saudi Aramco and Sumitomo Chemical.",
      "highlights": [
        "Improvement of working conditions.",
        "Improvement of employee productivity and work efficiency."
      ]
    }
  ],
  "education": [
    {
      "institution": "University of Washington",
      "url": "https://www.washington.edu/",
      "area": "Computer Science",
      "startDate": "2019-09-09",
      "endDate": "2024-06-13",
      "studyType": "Bachelor of Science",
      "courses": [
        "CSE 110 Computer Science Principles"
      ],
      "minors": [
        "Statistics"
      ]
    }
  ],
  "awards": [
    {
      "title": "Webby Nominee",
      "awarder": "Webby Awards",
      "date": "2020-06-21",
      "summary": "Multiple wins and nominations, including Best Navigation & Visual Design."
    }
  ],
  "certificates": [
    {
      "name": "Microsoft 365 Fundamentals Specialization",
      "issuer": "Kaggle",
      "date": "2025-02-01",
      "url": "https://www.coursera.org/specializations/microsoft-365-fundamentals"
    }
  ],
  "publications": [
    {
      "name": "Artificial Intelligence Spreading into the Marketing",
      "publisher": "Cal State Fullerton",
      "releaseDate": "2019-03-01",
      "url": "https://arxiv.org/html/2501.10388v2",
      "summary": "A retrospective study of how AI has impacted marketing."
    }
  ],
  "skills": [
    {
      "name": "Languages",
      "keywords": [
        "Javascript",
        "PHP",
        "Bash"
      ]
    },
    {
      "name": "Frameworks",
      "keywords": [
        "Vue",
        "React"
      ]
    }
  ],
  "languages": [
    {
      "language": "English",
      "fluency": "Fluent"
    },
    {
      "language": "Korean",
      "fluency": "Beginner"
    }
  ],
  "interests": [
    {
      "name": "Outdoor activities",
      "keywords": [
        "Running",
        "Hiking"
      ]
    },
    {
      "name": "Travel"
    }
  ],
  "references": [
    {
      "name": "Jeff Archibald",
      "reference": "There are few people better-suited for a design, creative, or innovation-focused leadership role within an organization tasked with delivering outcomes above the norm."
    }
  ],
  "projects": [
    {
      "name": "Graduation project",
      "description": "Omniboard Runtime",
      "highlights": [
        "Development of a versatile and accessible Flipper execution engine on Raspberry allowing to replace defective electronic boards during renovation.",
        "Acquired skills in management of a long term project, agile method, presentation of a project, managing a team."
      ],
      "startDate": "2018-09-21",
      "url": "https://omniboard-runtime.co.uk/",
      "roles": [
        "manager"
      ]
    }
  ]
}
